services:
  - type: web
    name: chauthanhev
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
